name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  redeploy_on_render:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger redeploy
        run: |
        curl -X GET \
        https://api.render.com/deploy/srv-cpvgs5pu0jms73asia7g?key=j6oOAipshH8